'use client';
import RecipeLayout, { RecipeData } from '../_components/RecipeLayout';

const recipe: RecipeData = {
    slug: 'so-huyet-nuong-mo-hanh',
    title: 'Sò Huyết Nướng Mỡ Hành (Blood Cockles Grilled with Spring Onion Oil)',
    subtitle: 'Live blood cockles placed directly on charcoal until the shells open and the briny, iron-rich flesh inside is barely cooked — finished with a spoonful of sizzling spring onion oil and crispy fried shallots that pool inside each open shell. The southern Vietnamese nhậu shellfish that is simultaneously the simplest and most addictive preparation on any charcoal grill.',
    category: 'APPETIZER',
    difficulty: 'Easy',
    totalTime: '20 min',
    rating: 4.9,
    baseServings: 4,
    heroImage: '/images/recipes/so-huyet-nuong-mo-hanh.jpg',
    intro: `Sò huyết nướng mỡ hành is the blood cockle preparation that dominates the nhậu shellfish menu throughout southern Vietnam — from the seafood restaurants along the coast of Vũng Tàu to the street food stalls of Saigon's Bình Thạnh district to the waterside restaurants of the Mekong Delta. Sò huyết — Tegillarca granosa, the blood cockle or blood clam, named for the red hemoglobin-rich blood that flows from the shells when they are opened and that stains the hands and makes the flesh appear deeply red — is the most iron-rich shellfish commonly eaten in Vietnam and has a specific flavor that is more intensely mineral than any other Vietnamese bivalve: briny, slightly metallic from the hemoglobin, and sweet in a way that is specific to this cockle's particular water filtration character. The nướng mỡ hành preparation applies the minimum possible cooking to these cockles: they are placed directly on hot charcoal, shell-side down, for 3-5 minutes — just long enough for the heat to conduct through the bottom shell and barely cook the flesh inside while the top shell pops slightly open from the steam generated by the cockle's own moisture. The flesh at this point is barely cooked — warm, slightly firm at the surface but still raw-adjacent in the center, in the specific state that Vietnamese diners call "chín tới" (just cooked). The mỡ hành — spring onion oil, made by pouring smoking-hot oil over sliced green onions — is spooned into each open shell immediately, where it mixes with the cockle's natural briny liquid and the blood that has pooled inside. The combination of the barely-cooked mineral-sweet cockle, the rendered cockle blood, and the hot spring onion oil in the open shell is the specific flavor experience that makes sò huyết nướng mỡ hành one of the most requested dishes at any southern Vietnamese nhậu session.`,
    ingredientSections: [
        {
            title: 'Blood cockles',
            items: [
                { amount: 1, unit: 'kg', name: 'live blood cockles (sò huyết)', note: 'alive — the shells should be tightly closed or close immediately when touched. The red blood visible at the shell opening is the sign of a live, healthy cockle. Available at Vietnamese and Asian seafood markets.' },
                { amount: 2, unit: 'tbsp', name: 'salt', note: 'for the purging water' },
            ],
        },
        {
            title: 'Mỡ hành (spring onion oil)',
            items: [
                { amount: 6, name: 'spring onions', note: 'green parts only, thinly sliced — the generous quantity is essential' },
                { amount: 80, unit: 'ml', name: 'neutral oil', note: 'heated to genuinely smoking — 210°C' },
                { amount: 0.5, unit: 'tsp', name: 'salt' },
                { amount: 4, unit: 'tbsp', name: 'crispy fried shallots (hành phi)', note: 'scattered over the shells after the mỡ hành' },
            ],
        },
        {
            title: 'Dipping sauce',
            items: [
                { amount: 3, unit: 'tbsp', name: 'fish sauce' },
                { amount: 2, unit: 'tbsp', name: 'fresh lime juice' },
                { amount: 1, unit: 'tbsp', name: 'sugar' },
                { amount: 3, unit: 'tbsp', name: 'water' },
                { amount: 2, name: 'garlic cloves', note: 'minced' },
                { amount: 2, name: 'bird\'s eye chilies', note: 'minced' },
                { amount: 1, unit: 'tbsp', name: 'fresh ginger', note: 'minced — ginger in the dipping sauce cuts through the mineral richness of the blood cockle' },
            ],
        },
        {
            title: 'To serve',
            items: [
                { amount: 1, name: 'bunch Vietnamese coriander (rau răm)', note: 'the essential herb for blood cockles throughout Vietnam' },
                { amount: 2, name: 'extra limes' },
                { amount: 2, name: 'fresh red chilies, sliced' },
                { amount: 1, name: 'bowl warm water with lime', note: 'finger bowl — blood cockles stain fingers red' },
            ],
        },
    ],
    steps: [
        {
            title: 'Purge the blood cockles — 30 minutes',
            description: 'Place live blood cockles in a large basin of salted water for 30 minutes. They will expel sand and organic matter. Unlike freshwater snails, blood cockles purge quickly — 30 minutes is sufficient. Rinse under cold running water, scrubbing each shell briefly with a brush. The shells should be tightly closed or close when touched. Any open shells that do not close when touched and smell of decay should be discarded. Note: the red blood visible at the shell opening of a live cockle is correct and a sign of freshness, not damage.',
            tip: 'The red blood at the opening of a live blood cockle is hemoglobin — the same oxygen-carrying molecule in human blood. It is what makes blood cockles distinctive in flavor and what gives them their name. First-time buyers sometimes mistake this redness for damage. It is the opposite: it is the sign of a healthy, fresh cockle with good blood content.',
        },
        {
            title: 'Build the charcoal fire',
            description: 'Light hardwood charcoal and wait until fully ashed over. For sò huyết nướng, the fire should be medium-hot to hot — the cockles need sufficient heat to conduct through the shell and barely cook the flesh in 3-5 minutes. Too cool and the flesh stays raw and the shell does not open; too hot and the flesh overcooks before the mỡ hành can be applied. Hold your hand 15cm above the coals — 3 seconds before the heat is too intense is the correct temperature.',
            tip: 'The temperature calibration for sò huyết nướng is more precise than for most charcoal preparations because the window between the shell opening (correct) and the flesh overcooking (incorrect) is narrow. A thermometer is not necessary — the 3-second hand test is the traditional and reliable method.',
        },
        {
            title: 'Grill shell-side down — 3-5 minutes',
            description: 'Place the blood cockles flat-side down (the flat top shell facing up, the rounded bottom shell on the coals) directly on the charcoal grate. The rounded bottom shell conducts heat; the flat top shell will pop open when the interior has heated through. Grill for 3-5 minutes. The shells will begin to open at the correct moment — a gap of 3-5mm appearing between the shells. This is the signal to remove. The flesh inside should be barely set — warm, slightly pink-red from the blood, and yielding.',
            tip: 'The moment the shell begins to open is the moment to remove — not after the shell has fully opened, which indicates overcooking. The correct state: the top shell has lifted 3-5mm but has not fallen back, the flesh inside is warm and still carrying its red-blood color throughout, not grey-white (overcooked). This specific doneness is what makes sò huyết nướng mỡ hành the dish it is.',
        },
        {
            title: 'Make the mỡ hành',
            description: 'Slice spring onion greens and place in a heatproof bowl with salt. Heat neutral oil in a small pan until genuinely smoking — 210°C, the temperature at which oil ripples rapidly and begins to smoke. Pour the smoking oil directly over the spring onions in one motion — it will sizzle loudly and the onions will turn from raw green to cooked green in seconds. Stir immediately. Have the mỡ hành ready before the cockles come off the fire.',
            tip: 'The smoking oil is not optionally hot — it must be genuinely smoking at 210°C for the spring onion to bloom correctly. Oil that is merely warm produces limp, raw-tasting spring onion. Oil at 210°C produces the specific cooked-and-fragrant spring onion that is the aromatic backbone of mỡ hành.',
        },
        {
            title: 'Apply mỡ hành immediately',
            description: 'Remove the opened cockles from the charcoal. Spoon a small amount of mỡ hành into each open shell immediately — the sizzling oil mixes with the cockle\'s natural briny liquid and the blood that has pooled inside the shell. The combination of hot oil and cockle blood produces a deeply savory, mineral-rich sauce inside each shell. Scatter crispy fried shallots over the cockles. Serve immediately with the ginger-nước chấm and rau răm.',
            tip: 'The mỡ hành must go into the shells while they are still hot from the charcoal — the shell retains heat and continues warming the oil and the cockle flesh for 2-3 minutes after removal from the fire. Cold cockles with hot mỡ hành produce a different, less integrated result than hot cockles with hot mỡ hành.',
        },
        {
            title: 'Eat — the blood cockle eating method',
            description: 'Pick up each cockle by the open shell. Tilt the shell to bring the cockle flesh, the blood liquid, and the mỡ hành to the opening. Use a small fork, toothpick, or the tip of a chopstick to loosen the cockle from its shell — it should come free with minimal effort if correctly cooked. Eat the cockle whole, with a leaf of rau răm, dipped briefly in the ginger nước chấm. Sip the blood-oil-brine liquid remaining in the shell before placing it aside. This sequence — cockle, rau răm, dip, sip — is the correct eating rhythm.',
            tip: 'The blood liquid remaining in the shell after the cockle has been eaten is the concentrated essence of sò huyết nướng mỡ hành — cockle blood, the cockle\'s own brine, and the mỡ hành oil combined. Experienced sò huyết eaters tilt each shell to their lips for this liquid before discarding the shell. It is not squeamishness that prevents first-timers from doing this — it is unfamiliarity. Once tasted, it becomes automatic.',
        },
    ],
};

export default function Page() {
    return <RecipeLayout recipe={recipe} />;
}
